# Generated by Django 3.1 on 2022-07-14 12:57

import Board.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='filename',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='file_upload',
            field=models.FileField(blank=True, upload_to=Board.models.get_file_path),
        ),
    ]
